### ISSUE TITLE
Benjamin Kaduk - Discuss 2

### ISSUE THREAD

**Issue by iffy50** [iffy50/draft-ietf-softwire-yang#13]
The binding-table-versioning container's "version" leaf is of type uint64
but the in-module description indicates that it is a timestamp.  If it is
actually supposed to be a timestamp, then the units and zero time need to
be specified, but it seems more likely that this should just be described
as an abstract version number, if I understand the prose text about this
container correctly.

**Comment by boucadair** [comment]
copy-paste problem. Fixed
