### ISSUE TITLE
Alissa Cooper - Comment 1

### ISSUE THREAD

**Issue by iffy50** [iffy50/draft-ietf-softwire-yang#15]
----------------------------------------------------------------------
COMMENT:
----------------------------------------------------------------------

I think "external party" would make more sense than "abuse party."

**Comment by iffy50** [comment]
‘party victim’ is a little awkward.I propose  the following:

When a party who is the victim of abuse presents an external IP address/port,

As this comment is still open with Alissa, I’ll propose the reword.

**Comment by boucadair** [comment]
Works for me. Thanks.
