### ISSUE TITLE
Banjamin Kaduk - Comment 3

### ISSUE THREAD

**Issue by iffy50** [iffy50/draft-ietf-softwire-yang#9]
Section 5.2

  o  softwire-num-max: used to set the maximum number of softwire
     binding rules that can be created on the lw4o6 element
     simultaneously.  This paramter must not be set to zero because
     this is equivalent to disabling the BR instance.

This seems to leave it ambiguous whether a server should reject an attempt
to set it to zero, or accept it but diable the BR instance.

**Comment by boucadair** [comment]
The text is clear.
range "1..max". 

No change is needed.
